// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package deltabot

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SetMakerUser is the `setMakerUser` instruction.
type SetMakerUser struct {
	MakerUser *ag_solanago.PublicKey
	Enable    *bool

	// [0] = [WRITE] gridBotState
	//
	// [1] = [WRITE] makerUsers
	//
	// [2] = [WRITE, SIGNER] user
	//
	// [3] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSetMakerUserInstructionBuilder creates a new `SetMakerUser` instruction builder.
func NewSetMakerUserInstructionBuilder() *SetMakerUser {
	nd := &SetMakerUser{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetMakerUser sets the "makerUser" parameter.
func (inst *SetMakerUser) SetMakerUser(makerUser ag_solanago.PublicKey) *SetMakerUser {
	inst.MakerUser = &makerUser
	return inst
}

// SetEnable sets the "enable" parameter.
func (inst *SetMakerUser) SetEnable(enable bool) *SetMakerUser {
	inst.Enable = &enable
	return inst
}

// SetGridBotStateAccount sets the "gridBotState" account.
func (inst *SetMakerUser) SetGridBotStateAccount(gridBotState ag_solanago.PublicKey) *SetMakerUser {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(gridBotState).WRITE()
	return inst
}

// GetGridBotStateAccount gets the "gridBotState" account.
func (inst *SetMakerUser) GetGridBotStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetMakerUsersAccount sets the "makerUsers" account.
func (inst *SetMakerUser) SetMakerUsersAccount(makerUsers ag_solanago.PublicKey) *SetMakerUser {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(makerUsers).WRITE()
	return inst
}

// GetMakerUsersAccount gets the "makerUsers" account.
func (inst *SetMakerUser) GetMakerUsersAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetUserAccount sets the "user" account.
func (inst *SetMakerUser) SetUserAccount(user ag_solanago.PublicKey) *SetMakerUser {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(user).WRITE().SIGNER()
	return inst
}

// GetUserAccount gets the "user" account.
func (inst *SetMakerUser) GetUserAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *SetMakerUser) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *SetMakerUser {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *SetMakerUser) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst SetMakerUser) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetMakerUser,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetMakerUser) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetMakerUser) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.MakerUser == nil {
			return errors.New("MakerUser parameter is not set")
		}
		if inst.Enable == nil {
			return errors.New("Enable parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.GridBotState is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.MakerUsers is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.User is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *SetMakerUser) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetMakerUser")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("MakerUser", *inst.MakerUser))
						paramsBranch.Child(ag_format.Param("   Enable", *inst.Enable))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta(" gridBotState", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("   makerUsers", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("         user", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj SetMakerUser) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `MakerUser` param:
	err = encoder.Encode(obj.MakerUser)
	if err != nil {
		return err
	}
	// Serialize `Enable` param:
	err = encoder.Encode(obj.Enable)
	if err != nil {
		return err
	}
	return nil
}
func (obj *SetMakerUser) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `MakerUser`:
	err = decoder.Decode(&obj.MakerUser)
	if err != nil {
		return err
	}
	// Deserialize `Enable`:
	err = decoder.Decode(&obj.Enable)
	if err != nil {
		return err
	}
	return nil
}

// NewSetMakerUserInstruction declares a new SetMakerUser instruction with the provided parameters and accounts.
func NewSetMakerUserInstruction(
	// Parameters:
	makerUser ag_solanago.PublicKey,
	enable bool,
	// Accounts:
	gridBotState ag_solanago.PublicKey,
	makerUsers ag_solanago.PublicKey,
	user ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *SetMakerUser {
	return NewSetMakerUserInstructionBuilder().
		SetMakerUser(makerUser).
		SetEnable(enable).
		SetGridBotStateAccount(gridBotState).
		SetMakerUsersAccount(makerUsers).
		SetUserAccount(user).
		SetSystemProgramAccount(systemProgram)
}
