// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package deltabot

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SetOwner is the `setOwner` instruction.
type SetOwner struct {

	// [0] = [] newOwnerId
	//
	// [1] = [WRITE] gridBotState
	//
	// [2] = [WRITE, SIGNER] user
	//
	// [3] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSetOwnerInstructionBuilder creates a new `SetOwner` instruction builder.
func NewSetOwnerInstructionBuilder() *SetOwner {
	nd := &SetOwner{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetNewOwnerIdAccount sets the "newOwnerId" account.
func (inst *SetOwner) SetNewOwnerIdAccount(newOwnerId ag_solanago.PublicKey) *SetOwner {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(newOwnerId)
	return inst
}

// GetNewOwnerIdAccount gets the "newOwnerId" account.
func (inst *SetOwner) GetNewOwnerIdAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetGridBotStateAccount sets the "gridBotState" account.
func (inst *SetOwner) SetGridBotStateAccount(gridBotState ag_solanago.PublicKey) *SetOwner {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(gridBotState).WRITE()
	return inst
}

// GetGridBotStateAccount gets the "gridBotState" account.
func (inst *SetOwner) GetGridBotStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetUserAccount sets the "user" account.
func (inst *SetOwner) SetUserAccount(user ag_solanago.PublicKey) *SetOwner {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(user).WRITE().SIGNER()
	return inst
}

// GetUserAccount gets the "user" account.
func (inst *SetOwner) GetUserAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *SetOwner) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *SetOwner {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *SetOwner) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst SetOwner) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetOwner,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetOwner) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetOwner) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.NewOwnerId is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.GridBotState is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.User is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *SetOwner) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetOwner")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("   newOwnerId", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta(" gridBotState", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("         user", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj SetOwner) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *SetOwner) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewSetOwnerInstruction declares a new SetOwner instruction with the provided parameters and accounts.
func NewSetOwnerInstruction(
	// Accounts:
	newOwnerId ag_solanago.PublicKey,
	gridBotState ag_solanago.PublicKey,
	user ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *SetOwner {
	return NewSetOwnerInstructionBuilder().
		SetNewOwnerIdAccount(newOwnerId).
		SetGridBotStateAccount(gridBotState).
		SetUserAccount(user).
		SetSystemProgramAccount(systemProgram)
}
